platzigram/platzigram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

     path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/posts/urls.py
""" Post urls """

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='', 
        view=views.PostsFeedView.as_view(), 
        name='feed'
    ),
    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/new/', 
        view=views.CreatePostView.as_view(), 
        name='create'
    ),
]

platzigram/users/urls.py
""" User urls """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(), name='login'),
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup'),
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update'),
]
    
    

platzigram/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    """ Profile model
    Proxy model that extends the base data  with other
    information.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True) 
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Return usernames """
        return self.user.username

platzigram/users/forms.py
from django import forms
from django.contrib.auth.models import User

from users.models import Profile

class SignupForm(forms.Form):
    """ Signup form """
    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput())

    def clean_username(self):
        """ Username must be unique """
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use')
        return username

    def clean(self):
        """ Verify password confirmation match. """
        data = super().clean()

        password = data['password']
        confirm_password = data['confirm_password']

        if password != confirm_password:
            raise forms.ValidationError('Password do not match')
        return data
    
    def save(self):
        """ Create user and profile """
        data = self.cleaned_data
        data.pop('confirm_password')

        user = User.objects.create_user(**data)
        profile = Profile(user=user) 
        profile.save()

"""
class ProfileForm(forms.Form):
    username = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    website = forms.URLField(max_length=200, required=False)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    email = forms.EmailField(max_length=200)
    picture = forms.ImageField() 
"""

platzigram/users/views.py
# Django
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile

from django.views.generic import DetailView, FormView, UpdateView

# Forms
from users.forms import SignupForm

# Create your views here.
class UserDetailView(LoginRequiredMixin, DetailView):
    """ User detail view. """
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

class SignupView(FormView):
    """ Users sign up view. """
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """ Save form data """
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'phone_number', 'biography', 'picture']

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

class LoginView(auth_views.LoginView):
    """ Login view """
    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """ Logout view """
    template_name = 'users/logged_out.html'

"""
def login_view(request):
    # Login view    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html', {'error': 'Username y contraseña invalido'})

    return render(request, 'users/login.html')
"""

def signup_view(request):
    """Signup view"""
    # import pdb; pdb.set_trace()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form.SignupForm()

    return render(
        request=request, 
        template_name='users/signup.html', 
        context={'form': form}
    )  
          
"""
@login_required
def update_profile(request):
    # Update profile view
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            #print(form.cleaned_data)  
            data = form.cleaned_data

            profile.username = data['username']
            profile.first_name = data['first_name']
            profile.last_name = data['last_name']
            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.email = data['email']
            profile.save()

            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect(url)   
    else:
        form = ProfileForm()    

    # Update view
    return render(
        request=request, 
        template_name='users/update_profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form,
        }
    )  
"""

"""
@login_required
def logout_view(request):
    # Logout a user.
    logout(request)
    return redirect('users:login')
"""

platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img 
                src="{{ user.profile.picture.url }}" 
                alt="@{{ user.username}}" 
                class="rounded-circle" 
                width="150px" height="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url 'users:update' %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ posts|length }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.pk %}" class="border">
                    <img src="{{ post.image_field.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

platzigram/templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Platzigram Sign in</title>
{% endblock %}

{% block container %}
{% if form.errors %}
<p class="alert alert-danger">Your username and password didn't match. Please try again.</p>
{% endif %}
<form action="{% url 'users:login' %}" method="POST" class="text-center">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" placeholder="Username" name="username" id="username" class="form-control" required="" autofocus=""/>
    </div>
    <div class="form-group">
        <input type="password" placeholder="Contraseña" name="password" id="password" class="form-control" required=""/>
    </div>
    <button type="submit" class="btn btn-primary btn-block mt-5">Iniciar sesión</button> 
</form>
<p class="mt-4">
    ¿No tienes una cuenta todavía? <a href="{% url 'users:signup' %}" class="btn btn-link">Registrate aquí</a>
</p> 
{% endblock %}

platzigram/templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Platzigram Sign in</title>
{% endblock %}

{% block container %}
{% if error %}
<p class="alert alert-danger">{{ error }}</p>
{% endif %}
<form action="{% url 'users:signup' %}" method="POST" class="text-center">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-block mt-5">Registrarse</button>
</form>
<p class="mt-4">
    ¿Ya tienes una cuenta? <a href="{% url 'users:login' %}" class="btn btn-link">Inicia sesión aquí</a>
</p> 
{% endblock %}

platzigram/templates/users/update_profile.html
{% extends 'base.html' %}

{% block head_content %}
<title>@{{ user.username }} | Update profile</title>
{% endblock %}

{% load static %}

{% block container %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" alt="" width="50" height="50" />
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" alt="" height="50" />
                    {% endif %}
                    
                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div> 
                
                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{ error }}
                    </div>
                {% endfor %}
                    
                <hr><br>   
                <div class="form-group">
                    <input 
                    type="text" 
                    placeholder="Username" 
                    name="username" 
                    id="username" 
                    class="form-control {% if form.username.errors %}is-invalid{% endif %}" 
                    value="{% if form.errors %}{{ form.username.value }}{% else %}{{ user.username }}{% endif %}" 
                    required="true" 
                    autofocus=""/>
                </div> 
                {% for error in form.username.errors %}
                    <div class="alert alert-danger">
                        <b>Username: </b>{{ error }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input 
                    type="text" 
                    placeholder="Nombre" 
                    name="first_name" 
                    id="first_name" 
                    class="form-control {% if form.first_name.errors %}is-invalid{% endif %}" 
                    value="{% if form.errors %}{{ form.first_name.value }}{% else %}{{ user.first_name }}{% endif %}" 
                    required="true"/>
                </div>
                {% for error in form.first_name.errors %}
                    <div class="alert alert-danger">
                        <b>First name: </b>{{ error }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input 
                    type="text" 
                    placeholder="Apellido" 
                    name="last_name" 
                    id="last_name" 
                    class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" 
                    value="{% if form.errors %}{{ form.last_name.value }}{% else %}{{ user.last_name }}{% endif %}" 
                    required="true" />
                </div>
                {% for error in form.last_name.errors %}
                    <div class="alert alert-danger">
                        <b>Last name: </b>{{ error }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input 
                        type="url" 
                        placeholder="Website" 
                        name="website" 
                        id="website" 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>    
                </div> 
                <div class="form-group">
                    <textarea 
                    class="form-control {% if form.biography.errors %}is-invalid{% endif %}" 
                    name="biography" 
                    placeholder="Biografía">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                </div>
                {% for error in form.biography.errors %}
                    <div class="alert alert-danger">
                        <b>Biography: </b>{{ error }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input 
                    type="text" 
                    placeholder="Celular" 
                    name="phone_number" 
                    id="phone_number" 
                    class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}" 
                    value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"/>
                </div>
                {% for error in form.phone_number.errors %}
                    <div class="alert alert-danger">
                        <b>Phone number: </b>{{ error }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input 
                    type="email" 
                    placeholder="Correo" 
                    name="email" 
                    id="email" 
                    class="form-control {% if form.email.errors %}is-invalid{% endif %}" 
                    value="{% if form.errors %}{{ form.email.value }}{% else %}{{ user.email }}{% endif %}" 
                    required="true"/>
                </div>
                {% for error in form.email.errors %} 
                    <div class="alert alert-danger">
                        <b>Email: </b>{{ error }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary btn-block mt-5">Actualizar info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}